lr: 0.0005
lr_patience: 3
weight_decay: 0.0001
max_epochs: 350
batch_size: 64
num_workers: 1
seed: 42
self_contrast: false
temperature: 0.07
momentum_betas:
- 0.9
- 0.95
lora: false
lora_rank: 4
lora_checkpoint_dir: ./.checkpoints/lora
lora_layer_idxs: null
lora_modality_names: null
linear_probing: false
