batch_size: 12
device: cuda:2
linear_probing: false
lora: false
lora_checkpoint_dir: ./.checkpoints/lora
lora_layer_idxs:
  text: null
  vision: null
lora_modality_names:
- vision
- text
lora_rank: 4
lr: 5.0e-06
max_epochs: 64
momentum_betas:
- 0.9
- 0.95
num_workers: 4
seed: 42
self_contrast: false
temperature: 0.01
weight_decay: 0.0001
